/**
 * Ale's Phase 0 bags — extraction + pins verified in phase0/results.json.
 * These populate the atlas on first launch so the map is rewarding at N=1.
 * They are `private`-tier scans, not reviewed global data (PRD tiering).
 */
import type { CoffeeEntry } from './types';

const CREATED = '2026-07-06T22:00:00.000Z';

export const SEED_COFFEES: CoffeeEntry[] = [
  {
    id: 'p0-archers-daye-bensa',
    createdAt: CREATED,
    source: 'private',
    roaster: 'Archers',
    roasterLocation: null,
    roasterPin: null,
    coffeeName: 'Ethiopia Daye Bensa Cold Ferment Honey (Archers Lot EP)',
    country: 'Ethiopia',
    regionString: 'Hamasho Village, Sidama Bensa',
    producerOrFarm: 'Hamasho Village',
    elevation: '2,230-2,300 masl',
    variety: '74158',
    process: 'Cold Ferment Honey',
    tastingNotes: 'yuzu, peach, ginger ale, earl grey',
    originPin: {
      tier: 'subregion',
      lat: 6.6507504,
      lon: 38.4796794,
      matched: 'Sidama, Ethiopia',
      query: 'Sidama, Ethiopia',
    },
  },
  {
    id: 'p0-sightglass-la-magdalena',
    createdAt: CREATED,
    source: 'private',
    roaster: 'Sightglass',
    roasterLocation: 'San Francisco, USA',
    roasterPin: null,
    coffeeName: 'Colombia La Magdalena',
    country: 'Colombia',
    regionString: 'La Magdalena, Tolima',
    producerOrFarm: null,
    elevation: null,
    variety: null,
    process: null,
    tastingNotes: 'toffee, concord grape, red apple',
    originPin: {
      tier: 'subregion',
      lat: 4.1545329,
      lon: -74.8702198,
      matched: 'La Magdalena, Espinal, Tolima, Colombia',
      query: 'La Magdalena, Tolima, Colombia',
    },
  },
  {
    id: 'p0-unido-geishify',
    createdAt: CREATED,
    source: 'private',
    roaster: 'Unido Panama Coffee Roasters',
    roasterLocation: 'Panama',
    roasterPin: null,
    coffeeName: 'Geishify (geisha espresso blend)',
    country: 'Panama',
    regionString: null,
    producerOrFarm: null,
    elevation: null,
    variety: '60% Catuai, 40% Geisha',
    process: 'Natural',
    tastingNotes: 'sandía, dulce de leche, hierba limón',
    originPin: {
      tier: 'country',
      lat: 8.559559,
      lon: -81.1308434,
      matched: 'Panamá',
      query: 'Panama',
    },
  },
  {
    id: 'p0-boy-bear-shoondisa',
    createdAt: CREATED,
    source: 'private',
    roaster: 'The Boy & The Bear',
    roasterLocation: null,
    roasterPin: null,
    coffeeName: 'Shoondisa',
    country: 'Ethiopia',
    regionString: 'Guji',
    producerOrFarm: 'Sookoo Coffee',
    elevation: null,
    variety: 'Ethiogibirinna 74110, Serto 74112',
    process: 'Natural',
    tastingNotes: 'bergamot, pear, candied lemon',
    originPin: {
      tier: 'subregion',
      lat: 5.5501401,
      lon: 39.2030529,
      matched: 'Guji, Oromia, Ethiopia',
      query: 'Guji, Ethiopia',
    },
  },
  {
    id: 'p0-equator-las-rosas',
    createdAt: CREATED,
    source: 'private',
    roaster: 'Equator Coffees',
    roasterLocation: null,
    roasterPin: null,
    coffeeName: 'Las Rosas',
    country: 'Colombia',
    regionString: 'Huila',
    producerOrFarm: null,
    elevation: null,
    variety: 'Caturra, Castillo',
    process: 'Washed',
    tastingNotes: 'dried cherry, date, cocoa powder',
    originPin: {
      tier: 'subregion',
      lat: 2.4738993,
      lon: -75.5900113,
      matched: 'Huila, Colombia',
      query: 'Huila, Colombia',
    },
  },
  {
    id: 'p0-feast-palmera',
    createdAt: CREATED,
    source: 'private',
    roaster: 'Feast Coffee & Culture',
    roasterLocation: null,
    roasterPin: null,
    coffeeName: 'Palmera',
    country: 'Colombia',
    regionString: 'Huila',
    producerOrFarm: null,
    elevation: '1600m',
    variety: 'Caturra, Castillo',
    process: 'Washed',
    tastingNotes: 'molasses, nougat, orange',
    originPin: {
      tier: 'subregion',
      lat: 2.4738993,
      lon: -75.5900113,
      matched: 'Huila, Colombia',
      query: 'Huila, Colombia',
    },
  },
  {
    id: 'p0-boy-bear-dynamic-espresso',
    createdAt: CREATED,
    source: 'private',
    roaster: 'The Boy & The Bear',
    roasterLocation: null,
    roasterPin: null,
    coffeeName: 'Dynamic Espresso',
    country: null,
    regionString: null,
    producerOrFarm: null,
    elevation: null,
    variety: null,
    process: null,
    tastingNotes: 'dark chocolate, caramel, red apples',
    originPin: null, // no origin printed on the box — stays in history, unplotted
  },
];
